# Every time I push to repo, run ShellCheck GitHub Action wrapper to ensure proper error-free syntax
name: CI - ShellCheck for bash scripts

on:
  push:
    branches: ["main"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run ShellCheck wrapper
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error

